// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace arch_seperate.Models
{
    public partial class Article
    {
        public long id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public bool ArticleRead { get; set; }
        public Guid UserId { get; set; }

        public virtual User User { get; set; }
    }
}