// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using arch_seperate.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace arch_seperate.Models
{
    public partial class BlogContext
    {
        private IBlogContextProcedures _procedures;

        public virtual IBlogContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BlogContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBlogContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class BlogContextProcedures : IBlogContextProcedures
    {
        private readonly BlogContext _context;

        public BlogContextProcedures(BlogContext context)
        {
            _context = context;
        }

        public virtual async Task<int> resetTableIdentiyAsync(string table, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "table",
                    Size = 60,
                    Value = table ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[resetTableIdentiy] @table", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
