// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace arch_seperate.Models
{
    public partial class ExamResult
    {
        [DisplayName("StudentName")]
        public string StudentName { get; set; }

        [DisplayName("Subject")]
        public string Subject { get; set; }

        [DisplayName("Marks")]
        public int? Marks { get; set; }
    }
}